[tool.black]
line-length = 120
# required-version = '21.8b0' # see https://github.com/psf/black/issues/2493
target-version = ["py38"]


[tool.isort]
line_length = 120
profile = "black"
multi_line_output = 3
known_third_party = ["pykov", "autoslug", "jsonfield", "mock", "parsy", "aldjemy", "django_ftl", "fluent", "django"]
skip_glob = ["**/migrations/*.py", "node_modules/*", "**/elm-stuff/*", ".*", "config/trac/*"]
skip = ["settings.py", "node_modules", ".git", "learnscripture/static/elm" ]
