[tool.black]
line-length = 120
# required-version = '21.8b0' # see https://github.com/psf/black/issues/2493
target-version = ["py38"]


[tool.ruff]
line-length = 120
extend-select = [
  "UP",  # enable pyupgrade
  "I",  # enable isort
  "FLY", # enable flynt
]
target-version = 'py310'
ignore = ["E501","E731"]
